language: go

go:
  # - 1.7.4
  - 1.8.3
  - 1.9
  # - tip

os:
  - linux
  # - osx

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

before_install:
  - mkdir travis-phantomjs
  - wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
  - tar -xvf $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $PWD/travis-phantomjs
  - export PATH=$PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH

install:
  - go get -t ./...
  - go get github.com/golang/lint/golint
  - go get github.com/gordonklaus/ineffassign
  - phantomjs --version

script:
  # todo exclude vendors from diff or format them and commit
  #- diff <(echo -n) <(gofmt -s -d .)
  - go list -f '{{.Dir}}' ./... | grep -v /vendor/ | xargs -n 1 ineffassign
  - go vet $(go list ./... | grep -v /vendor/)
  - go test -race -count=4 $(go list ./... | grep -v /vendor/)

after_script:
  - golint $(go list ./... | grep -v /vendor/)
  - go test -run=ðŸ¤ -bench=. -count=1 -benchmem $(go list ./... | grep -v /vendor/)
